version: '3'
services:
  auth-app-db:
    container_name: auth-app-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=registration'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'